import type { Metadata } from "next";
import Link from "next/link";

import { SiteFooter, SiteHeader } from "../landing";

// Deliberately /site-map, not /sitemap: /sitemap.xml is generated by
// app/sitemap.ts for crawlers, and Next would route a /sitemap page into the
// same namespace. This is the human-readable counterpart -- every page a
// visitor can actually reach, in one list, which is also the thing the footer
// link promises.
//
// Every entry below is a route that really exists (verified against the app
// directory). A site map linking to a page that 404s is worse than no site map,
// especially on a product whose pitch is that its output can be trusted.
const TITLE = "Site map";
const DESCRIPTION = "Every page on PostMortem AI, in one list.";

export const metadata: Metadata = {
  title: `${TITLE} — PostMortem AI`,
  description: DESCRIPTION,
  alternates: { canonical: "https://www.nanoneuron.ai/site-map" },
  openGraph: {
    title: `${TITLE} — PostMortem AI`,
    description: DESCRIPTION,
    url: "https://www.nanoneuron.ai/site-map",
    type: "website",
  },
};

const GROUPS: { heading: string; links: { label: string; href: string; note: string }[] }[] = [
  {
    heading: "Product",
    links: [
      { label: "Home", href: "/", note: "What this is and the core loop" },
      { label: "Docs", href: "/docs", note: "How grounding, webhooks, MCP and payments actually work" },
      { label: "Published postmortems", href: "/postmortems", note: "Postmortems clients chose to publish publicly" },
      { label: "System status", href: "/status", note: "A live check against the backend and database" },
    ],
  },
  {
    heading: "Writing",
    links: [
      {
        label: "How grounding works",
        href: "/blog/grounding-mechanism",
        note: "Long-form: why a claim without a citation is removed rather than kept",
      },
      {
        label: "Real outage demo",
        href: "/blog/github-outage-demo",
        note: "A worked postmortem built from a real public incident",
      },
    ],
  },
  {
    heading: "Buying",
    links: [
      { label: "Pricing", href: "/pricing", note: "Monthly and annual, UPI and international wire" },
      { label: "Sales and refunds", href: "/pricing#refunds", note: "The 14-day refund terms" },
    ],
  },
  {
    heading: "Legal",
    links: [
      { label: "Privacy Policy", href: "/privacy", note: "What is stored, who it is shared with, and how erasure works" },
      { label: "Terms of Use", href: "/terms", note: "The agreement covering use of this service" },
    ],
  },
  {
    heading: "For machines",
    links: [
      { label: "sitemap.xml", href: "/sitemap.xml", note: "The crawler version of this page" },
      { label: "llms.txt", href: "/llms.txt", note: "Short index for AI assistants" },
      { label: "llms-full.txt", href: "/llms-full.txt", note: "Complete reference: API surface, architecture, verified behaviour" },
      { label: "security.txt", href: "/.well-known/security.txt", note: "How to report a security issue" },
    ],
  },
];

export default function SiteMapPage() {
  return (
    <>
      <SiteHeader />
      <main className="mx-auto max-w-2xl px-4 py-10">
        <div className="mb-8">
          <div className="text-xs font-medium tracking-widest text-muted uppercase">Site map</div>
          <h1 className="mt-2 text-3xl font-semibold tracking-tight text-ink">Every page, in one list</h1>
          <p className="mt-2 max-w-md text-sm text-muted">{DESCRIPTION}</p>
        </div>

        {GROUPS.map((group) => (
          <section key={group.heading} className="mb-8">
            <h2 className="mb-3 text-xs font-medium tracking-wide text-muted uppercase">{group.heading}</h2>
            <ul className="space-y-3">
              {group.links.map((link) => (
                <li key={link.href}>
                  {/* Machine-facing files are static assets, not app routes, so
                      they need a plain <a> -- next/link would try to
                      client-navigate to something that isn't a page. */}
                  {link.href.endsWith(".txt") || link.href.endsWith(".xml") ? (
                    <a className="text-sm font-medium text-ink underline underline-offset-2" href={link.href}>
                      {link.label}
                    </a>
                  ) : (
                    <Link className="text-sm font-medium text-ink underline underline-offset-2" href={link.href}>
                      {link.label}
                    </Link>
                  )}
                  <p className="mt-0.5 text-sm text-muted">{link.note}</p>
                </li>
              ))}
            </ul>
          </section>
        ))}
      </main>
      <SiteFooter />
    </>
  );
}
